### ISSUE TITLE
Add region setting for Minio

### ISSUE THREAD

**Issue by Gsyltc** [s3drive/app#20]
Hi,

When a region is set in Minio, it's mandotory to set the region value in order to connect to a bucket.

There is no possibility to set the region on the app.
Can you add the possibility to set a region ?

Got an exception : The header authorization is wrong. The region is malformed. Expecting 'the-region' 

Thanks

**Comment by tomekit** [comment]
Hi @Gsyltc,
Thanks for reporting this. 
May I ask you what's the use case for setting mandatory region value in your MinIO setup?
In principal, S3 providers except AWS doesn't require region to be specified.

We will aim to add that, unfortunately we will have to do some overhaul in order to accommodate this change, since with the AWS S3 client that we use setting custom/non-AWS region is not allowed.

**Comment by tomekit** [comment]
I am not sure if it helps, but in our other S3 app we've added MinIO region detection. That means that you don't need to specify region, but it will log you in anyway.
App: https://play.google.com/store/apps/details?id=com.s3.drive.file.explorer.storage.cloud.manager

Over the coming months the S3Drive app will contain all of the existing PhotoSync logic (including photo upload, upload constraints etc.).
We've got early release of a web client which is browser self-contained clone of the S3Drive app: https://web.s3drive.app/

**Comment by Gsyltc** [comment]
Thanks,

I will try it. I will inform you after the test

**Comment by tomekit** [comment]
Hi @Gsyltc, 
I was wondering if you had chance to see if this is still an issue for you.
Thanks

**Comment by Gsyltc** [comment]
Hi @tomekit. 
I just try with the S3 Drive application.

It works.

I will wait for the S3 drive updates with the new features.
Thanks :)

**Comment by tomekit** [comment]
That's great to hear. Given a chance to ask, what's are the features which have the highest priority for you?
Please find our roadmap items where you can vote/comment on existing ones and add any feature requests as you need: https://s3drive.canny.io/
