### ISSUE TITLE
File name encryption possible?

### ISSUE THREAD

**Issue by kzshantonu** [s3drive/app#22]
Hi,

Stumbled upon this on the backblaze subreddit. Looks promising so far!

How viable is it to implement filename encryption or at least obfuscation?

**Comment by kzshantonu** [comment]
I now see it was already requested. My bad

**Comment by tomekit** [comment]
Thanks, as you've already noticed it's on our roadmap here: https://s3drive.canny.io/feature-requests/p/filenamefilepath-encryption

We already have a working prototype, but then couple users requested if we could actually make it compatible with Rclone or other tooling, which slightly delays this, but hopefully for a good reason. Stay tuned !
