### ISSUE TITLE
failed to pay the bill

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#24]
I would like to pay self -hosted personal once plan 9.9 €, but there's an error when I tried to pay,it said "Failed to load Stripe.js" on Chrome and your website(https://s3drive.app/pricing), please fix it quickly case I need mixed cloud login!!
![image](https://user-images.githubusercontent.com/130731540/235354271-da8f50cd-7a28-467f-b2e1-b4cff1edd6ed.png)

**Comment by tomekit** [comment]
Hi @mix9311,
Sorry that you faced this problem. We are investigating this issue, as some % of our users is affected by this issue. On our end it seem to be working fine on Chrome.

I've enabled Pro on your account and you shall receive an e-mail directly from Stripe to handle payment.

There seem to be one more issue related to underlying account registration that we're working on and will have it resolved within an hour.

Can you please let me know what platform you are using? 

If you face any other problems, we're here to help. Thank you for your support !

**Comment by tomekit** [comment]
@mix9311 
Your should've received welcome e-mail from S3Drive meaning that your account is now set up correctly.

Speaking of Stripe issues. Is it possible that you're behind some corporate firewall?

**Comment by tomekit** [comment]
There is a guide for Backblaze which doesn't seem to be working on your end: https://github.com/s3drive/app/blob/master/INITIAL_SETUP.md however in principle the same rule applies. You need to register an account, create a bucket and the endpoint will be available on yoc.

For instance Wasabi endpoint looks like this: https://s3.eu-central-1.wasabisys.com

iDrive: https://f4n6.par.idrivee2-46.com
Storj: https://gateway.storjshare.io
Scaleway: https://s3.pl-waw.scw.cloud

**Comment by tomekit** [comment]
Please try the following payment link in case payment through our website doesn't work for you: https://buy.stripe.com/9AQ8AB1R6cjlgFibIJ

If this doesn't work, then we would have to find different payment method which is supported on your end and we're open for suggestions.

**Comment by tomekit** [comment]
It does seem that payment actually went through. Thank you for your support !
May I ask you how did you manage to get it working? (Feel free to send me a direct message at: tom@tr3.eu).

**Comment by tomekit** [comment]
Thanks for letting me know. I assume this resolved now.
