### ISSUE TITLE
10GB Free Storage - daily limits during file Move

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#30]
When subscribe S3 drive pro standalone，I uploaded my video but hard to move them to new dictionary，some errors here(will u fix it orThis operation cannot be performed, whether it is moving a file or multiple files)
![Screenshot_2023-05-04-20-06-33-255_com s3 drive file explorer storage cloud manager](https://user-images.githubusercontent.com/130731540/236199846-75de8764-b073-49ab-8344-8d298a45c108.jpg)

**Comment by tomekit** [comment]
S3Drive Pro Standalone is a self-hosted package that gives you additional functions and features on top of your own S3 endpoint(s).
If you have S3Drive account (regardless if with or without Pro Standalone package) you also can use our: "Free" package which comes with 10GB storage, but is subject to daily limits as listed in our website:
![Screenshot from 2023-05-04 14-14-35](https://user-images.githubusercontent.com/7759113/236201258-fb179e42-fa73-4fd6-b597-0576649b19fb.png)

Our managed accounts with monthly/yearly plans are not yet available, however they would come without any daily limits.
