### ISSUE TITLE
Audio and video preview function problem

### ISSUE THREAD

**Issue by mix9311** [s3drive/app#34]
When I try to click to preview my uploaded audio file, include flac, mp3 Waiting for the file format, I found that the display is a black playback interface. If I want to play a video, it doesn’t matter, but when the audio song is playing, it should have displayed a circular cover rotation player with lyrics on the right. Similar to player interface of apple music and Spotify , thank u.
![Screenshot_2023-05-29-23-38-34-760_com apple android music-edit](https://github.com/s3drive/app/assets/130731540/d5827f6b-c7a6-4c74-a816-b7c652724123)
![Screenshot_2023-05-29-23-37-57-818_com spotify music-edit](https://github.com/s3drive/app/assets/130731540/a42bf68d-648b-4d64-8f67-c1d5fb519fde)
![Screenshot_2023-05-29-23-37-43-623_com spotify music](https://github.com/s3drive/app/assets/130731540/e96c9f19-886c-443e-88d1-c93b500232ac)

**Comment by tomekit** [comment]
Thank you for your feedback. We've added this to our roadmap: https://s3drive.canny.io/feature-requests/p/implement-audiovideo-album-cover-display
