### ISSUE TITLE
E2E encryption: unable to decrypt files

### ISSUE THREAD

**Issue by jaimedelano** [s3drive/app#35]
Android app (version 1.2.13) does not decrypt files.
I unable to open files encrypted with S3Drive.

**Comment by jaimedelano** [comment]
Open function: I choose an app to open file, but no application can open the file;
Download (example a PDF): OK, but I can't open it, I get error message saying the file is corrupted;
Preview: [PDF] Can't open file, Cause: null | [Image] Gallery app shows a placeholder/broken picture.

Decryption does not work on desktop (Windows 11).

There is no error or warning message.

**Comment by jaimedelano** [comment]
I have tested it with a new file.
The file size is similar, but not the same. 
Original: 293,302 bytes
Encrypted: 293,318 bytes

**Comment by tomekit** [comment]
Size difference is expected. 16 bytes accounts for a verification and is appended to the encrypted blob. During decryption this 16 bytes verifies authenticity of a file.
More on that: https://stackoverflow.com/questions/67028762/why-aes-256-with-gcm-adds-16-bytes-to-the-ciphertext-size

**Comment by tomekit** [comment]
May I ask what's the error that you receive during decryption of this 293,318 bytes file?

**Comment by jaimedelano** [comment]
I don't receive any error. Can you add a verbose mode option in About / Logs?  
 
  Em sex., 30 30e jun. 30e 2023 às 19:11, Tom ***@***.***> escreveu:   


May I ask what's the error that you receive during decryption of this 293,318 bytes file?

**Comment by jaimedelano** [comment]
I confirm v1.4.1 has fixed it. Thanks!

**Comment by tomekit** [comment]
That's great to hear, thanks for letting me know !
