### ISSUE TITLE
App crashes when E2E encryption enabled

### ISSUE THREAD

**Issue by jaimedelano** [s3drive/app#36]
If I enable E2E encryption and try to upload a file, the desktop app (v1.2.12) closes immediately after I select a file and click open.
No message is shown.

**Comment by jaimedelano** [comment]
Windows 11. 
File size: 5,95KB

**Comment by tomekit** [comment]
This month we're going to release new encryption scheme (don't worry the old one will be supported for decryption) which will significantly reduce the memory footprint and should no longer cause any crashes. 
More on that here: https://s3drive.canny.io/feature-requests/p/implement-chunked-encryption-using-stream-protocol

I am going to close this issue, however if issue still present after we applying new (soon to be released) encryption scheme, feel free to reopen this issue. Thanks.
