### ISSUE TITLE
Bug with emojis in fileeditor

### ISSUE THREAD

**Issue by Morethanevil** [s3drive/app#37]
I use the Android app 1.4.5 and if I create a new file and use the internal editor, I can not save the file when an emoji is inside the file. Emoji in filenames are working and preview of textfiles woth emoji already included are working too

**Comment by tomekit** [comment]
We've developed a fix which will be released in a 1.4.7 version in a couple days. Thank you.

**Comment by Morethanevil** [comment]
Fixed with latest update :)
