### ISSUE TITLE
Improvement: filenames with date and time stamp instead of UUID

### ISSUE THREAD

**Issue by Morethanevil** [s3drive/app#38]
When I use the video function or taking a picture it is named with an UUID filename like 7a457568778e2791434752196171660.jpg

It would be better if filenames with date and time stamp are used, like in Android. Something like IMG-2023-07-31-00-05-13.jpg

**Comment by tomekit** [comment]
I do appreciate your effort to mention all of the improvements we could apply. 
I've added the roadmap item to track this: https://s3drive.canny.io/feature-requests/p/take-photo-record-video-filename-improvements
Thank you !

**Comment by Morethanevil** [comment]
Works fine now, thanks :)
