### ISSUE TITLE
Files without an extension are not backuped

### ISSUE THREAD

**Issue by Morethanevil** [s3drive/app#41]
I have some files on Android in a folder and some of them have no extension (048 048 - Test)

I wanted to use the media backup and it ignores those files. All other files are backup correctly.

Using Android 13
Oneplus 9 Pro
S3Drive 1.4.7

**Comment by tomekit** [comment]
Thanks for the report, I've moved this here: https://s3drive.canny.io/admin/feedback/feature-requests/p/files-without-an-extension-are-not-backed-up?boards=feature-requests

**Comment by tomekit** [comment]
We've release folder sync in our .APK release, we're awaiting permission approval from Google Team so we can include this feature in our Google Play release.
If you don't mind please try "Sync (new)" feature in our: https://docs.s3drive.app/install/#apk-release

**Comment by tomekit** [comment]
Since: "Sync" functionality was released in the official Android release (1.7.9) quite a while ago, I am going to close that one.
