### ISSUE TITLE
Improvement: Support for autofill from password managers

### ISSUE THREAD

**Issue by Morethanevil** [s3drive/app#42]
Autofillsupport would be great when adding a new profil or entering the encryption password. It is userul if Bitwarden or Keepass could fill in the right credentials directly

**Comment by tomekit** [comment]
We've added the relevant input hooks and included in 1.4.8 release (https://s3drive.app/changelog). We've briefly tested this with Bitwarden and Android which seem to be capturing fields properly at least on the e-mail/password login screen.

The issue that we've had is that we didn't exactly know what would be the best naming convention for all of the four fields that we use on the S3 login screen for the best auto-capture experience.This screen consists (access key id, secret, bucket name and endpoint). On Android we've used (AUTOFILL_HINT_USERNAME, AUTOFILL_HINT_PASSWORD, AUTOFILL_HINT_PERSON_NAME, url) respectively (https://developer.android.com/reference/androidx/autofill/HintConstants).

I would appreciate if you could let me know if this works for you.

Note: It was released on all platforms already except iOS which is awaiting Apple's approval.

**Comment by Morethanevil** [comment]
Works fine with bitwarden and it fills username and password. This is good enough. Bucket name changes per account and Domain is shorter than a password in most cases 

Autofill for E2EE fills the password, so it works fine too

**Comment by tomekit** [comment]
Thank you for your feedback and efforts to try things out. I consider this resolved now.
