### ISSUE TITLE
Black window in Windows 11

### ISSUE THREAD

**Issue by jaimedelano** [s3drive/app#44]
See attached screenshot.
Version: 1.5 (it happens in older versions too)
OS: Windows 11 21H1
https://i.imgur.com/BsaunRi.png

**Comment by tomekit** [comment]
Hi @jaimedelano,
Thanks for reporting.
What's your S3 provider?

**Comment by jaimedelano** [comment]
MinIO by Pydio Cells.
I don't think this is related to the S3 provider.
Sometimes the window elements are displayed (are visible). But this happens rarely.
The Windows Event Viewer does not report any errors.

**Comment by jaimedelano** [comment]
This glitch disappeared after I maximized the window.

**Comment by jaimedelano** [comment]
Fixed!

**Comment by tomekit** [comment]
Thanks for letting me know. We're in the process of updating some dependencies potentially related to this issue. Some improvements will be included in 1.5.1 release. This may or may not fix resolve this issue. 

If you're able to reproduce it on 1.5.1 or later versions, I would appreciate if you can reopen this issue.
