### ISSUE TITLE
add crypto option payment

### ISSUE THREAD

**Issue by contenidosonline** [s3drive/app#46]
Will it be possible to add crypto as a payment method? There are several platforms that can be used and it is an important option for people in countries where it is difficult to make payments with credit cards.

**Comment by tomekit** [comment]
Thanks for your feedback. There will certainly be such option available. Hard to give any ETA at this stage as we haven't exactly decided which way to integrate it into our billing system. Do you have specific crypto in mind or you don't mind?

**Comment by contenidosonline** [comment]
Hi Tom !


I use several web and vps hosting services, which use services such as:

- Coinbase payments
-Bitpay
-Coinify
- Coinpayments

I think it would be important to accept payments with low network fees, such as LTC or Ethereum layer II networks, since the BTC and ETH fees on their main networks may be higher than the s3drive service itself.

roberto

**Comment by tomekit** [comment]
We still have plans to implement crypto payments, it's just we've been prioritizing other items: https://s3drive.app/roadmap and https://s3drive.canny.io/feature-requests and weren't able to include crypto payments in 2024 roadmap.
We'll be executing this likely around 2025.

I've moved that here, as this is where keep feature requests: https://s3drive.canny.io/feature-requests/p/add-cryptocurrency-payment-option
