### ISSUE TITLE
Strato HiDrive S3 access problem

### ISSUE THREAD

**Issue by bolek2000** [s3drive/app#49]
I use version 1.7.2 flatpak in PopOS22.04 (Ubuntu based) and managed to find the right credentials to login to my account. 
In the files view the App says "Something went wrong" Access denied.
Provider side has no good documentation, so I do'nt know where to start.
Is there a logfile to track down the problem ?
Used this information:
https://help.arborxr.com/en/articles/6415292-strato-hidrive-s3-storage-bucket-configuration-requirements

Login only worked with following endpoint: https://eu-central-1.s3.hidrive.strato.com
Using https://s3.hidrive.strato.com gave "Region mismatch" error.

**Comment by tomekit** [comment]
Hi @bolek2000 and sorry for the late reply. In the: `[1.7.6] - 2024-01-25` release (https://s3drive.app/changelog), we've added support for custom provided region.
If S3 URL contained region: https://eu-central-1.s3.hidrive.strato.com/ we could detect that, but likely weren't able to do it using: https://s3.hidrive.strato.com/
There are some other methods of region detection, but it's possible that Strato doesn't support it, hence the failure.

Please update S3Drive to the newest version and then provide the: `eu-central-1` region (or the one that's correct) on the login screen:
![Screenshot from 2024-02-02 13-42-48](https://github.com/s3drive/app/assets/7759113/5cd43e5a-86d0-4c42-bf40-94f03ec23d9a)

Please let me know if that helped. Thanks !

**Comment by bolek2000** [comment]
@tomekit  I am on 1.7.8 now and  managed to test this again and now it works for me. Thank you for this great app, really appreciate your work, will now start doing more with it...
