### ISSUE TITLE
Cant access other drives on Windows for sync

### ISSUE THREAD

**Issue by dennisooki** [s3drive/app#50]
On windows, the folder picker doesnt list other drives/partitions mounted on my system.
This also happened on linux but i was still able to mount through /mnt, which may be considered a workaround idk.

**Comment by tomekit** [comment]
Thanks for your feedback.

We'll have this addressed, we weren't sure how to include other mounts without cluttering the view with not relevant mounts. 
It seems that each platform will have its own way of getting the mount list.

For instance on Ubuntu I get this:
E.g.: `findmnt -D -t nosquashfs,notmpfs,nodevtmpfs` returns:
```
/dev/mapper/ubuntu--vg-root ext4        543,2G 474,9G  40,7G  87% /
/dev/nvme0n1p4              ext4          1,7G 293,7M   1,3G  17% /boot
/dev/nvme0n1p1              vfat        548,9M    68M 480,9M  12% /boot/efi
portal                      fuse.portal                           /run/user/1000/doc
```
Perhaps we could allow user to provide custom path manually, e.g.: "D:\" or "/mysecondhdd"

**Comment by tomekit** [comment]
This is to let you know that we will release improvement in a next release.
We will allow to select custom location using system native directory picker.
![Screenshot from 2024-01-20 19-19-40](https://github.com/s3drive/app/assets/7759113/d8d61ceb-a490-4432-9605-33e6e52466e5)

**Comment by dennisooki** [comment]
Aight looks good 👍
