### ISSUE TITLE
deb installation does not open on ubuntu 22.04 (missing dependency

### ISSUE THREAD

**Issue by romaia** [s3drive/app#51]
Using ubuntu 22.04, when I try to open the application, I get an error due to a missing dependency

```
$ /usr/local/lib/s3drive/kapsa
/usr/local/lib/s3drive/kapsa: error while loading shared libraries: libmpv.so.2: cannot open shared object file: No such file or directory
```

It seems that ubuntu has only libmpv1 available, not 2.

The dependencies listed in the package are `Depends: libmpv1 | libmpv2`, sot it correctly installs, but its not loading.

**Comment by romaia** [comment]
AppImage also does not load.

Installing from flathub works.

**Comment by tomekit** [comment]
Hi, thanks for your report.

Can you please let me know what's the issue with the AppImage? Does any error appear in the console?
Is it also related to `libmpv`?

Speaking of `libmpv` versions, not sure if we can actually handle both libmpv1 and libmpv2 from a single .deb. It seems that we build .deb with `libmpv2`, so even though we provide an alternative in "Depends", the binary can't actually work with `libmpv1`. 
We've updated our build machine, as some users were complaining about missing `libmpv1` in their distribution.

We might need to add another build-line for 22.04 and older systems, we'll talk this through internally.

libmpv versions across distributions
```
https://packages.ubuntu.com/search?keywords=libmpv1
focal (20.04LTS) (libs): video player based on MPlayer/mplayer2 (client library) [universe]
0.32.0-1ubuntu1: amd64 arm64 armhf ppc64el riscv64 s390x
jammy (22.04LTS) (libs): video player based on MPlayer/mplayer2 (client library) [universe]
0.34.1-1ubuntu3: amd64 arm64 armhf ppc64el riscv64 s390x

https://packages.ubuntu.com/search?keywords=libmpv2
lunar (23.04) (libs): video player based on MPlayer/mplayer2 (client library) [universe]
0.35.1-2ubuntu1: amd64 arm64 armhf ppc64el riscv64 s390x
mantic (23.10) (libs): video player based on MPlayer/mplayer2 (client library) [universe]
0.36.0-1ubuntu1: amd64 arm64 armhf ppc64el riscv64 s390x 
```

I am glad that at least Flatpak release works fine for you though.

**Comment by tomekit** [comment]
Our AppImage was fixed and `libmpv2` was correctly included.

Our .deb package will now require strict `libmpv2` as app no longer can work with `libmpv1`.
If that's not available on your OS then the libmpv2 PPA will be required.

If this doesn't resolve your issue, please let me know, so I can reopen this. Thanks.
